/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as SupportRouteImport } from './routes/support'
import { Route as HealthSlugRouteImport } from './routes/health.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSlugRoute = HealthSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/coordinator': typeof CoordinatorRoute
  '/culture': typeof CultureRoute
  '/health': typeof HealthRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/school': typeof SchoolRoute
  '/support': typeof SupportRoute
  '/health/$slug': typeof HealthSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/coordinator': typeof CoordinatorRoute
  '/culture': typeof CultureRoute
  '/health': typeof HealthRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/school': typeof SchoolRoute
  '/support': typeof SupportRoute
  '/health/$slug': typeof HealthSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabinet': typeof CabinetRoute
  '/coordinator': typeof CoordinatorRoute
  '/culture': typeof CultureRoute
  '/health': typeof HealthRouteWithChildren
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/school': typeof SchoolRoute
  '/support': typeof SupportRoute
  '/health/$slug': typeof HealthSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cabinet'
    | '/coordinator'
    | '/culture'
    | '/health'
    | '/lab'
    | '/login'
    | '/register'
    | '/school'
    | '/support'
    | '/health/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cabinet'
    | '/coordinator'
    | '/culture'
    | '/health'
    | '/lab'
    | '/login'
    | '/register'
    | '/school'
    | '/support'
    | '/health/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cabinet'
    | '/coordinator'
    | '/culture'
    | '/health'
    | '/lab'
    | '/login'
    | '/register'
    | '/school'
    | '/support'
    | '/health/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CabinetRoute: typeof CabinetRoute
  CoordinatorRoute: typeof CoordinatorRoute
  CultureRoute: typeof CultureRoute
  HealthRoute: typeof HealthRouteWithChildren
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SchoolRoute: typeof SchoolRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$slug': {
      id: '/health/$slug'
      path: '/$slug'
      fullPath: '/health/$slug'
      preLoaderRoute: typeof HealthSlugRouteImport
      parentRoute: typeof HealthRoute
    }
  }
}

interface HealthRouteChildren {
  HealthSlugRoute: typeof HealthSlugRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthSlugRoute: HealthSlugRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CabinetRoute: CabinetRoute,
  CoordinatorRoute: CoordinatorRoute,
  CultureRoute: CultureRoute,
  HealthRoute: HealthRouteWithChildren,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SchoolRoute: SchoolRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
